var CONFIG = {
  EVENTS_SHEET_NAME: 'Coaching events',
  LEGACY_COACHING_SHEET_NAMES: ['Events', 'TrainingEvents'],
  NON_TRAINING_EVENTS_SHEET_NAME: 'Non-Coaching events',
  LEGACY_NON_COACHING_SHEET_NAMES: ['Non-Training Events'],
  RULES_SHEET_NAME: 'rules',
  SCRIPT_PROPERTY_KEYS: {
    API_KEY: 'API_KEY',
    CALENDAR_ID: 'CALENDAR_ID',
    ZOOM_ARCHIVE_SPREADSHEET_ID: 'ZOOM_ARCHIVE_SPREADSHEET_ID',
    DRIVE_INBOX_FOLDER_ID: 'DRIVE_INBOX_FOLDER_ID',
    CLIENT_MEETINGS_ROOT_FOLDER_ID: 'CLIENT_MEETINGS_ROOT_FOLDER_ID'
  },
  CALENDAR_ID: 'primary',
  LOOKBACK_DAYS: 7,
  LOOKAHEAD_DAYS: 30,
  ARCHIVE_AFTER_DAYS: 30,
  ZOOM_ARCHIVE_SHEET_NAME: 'zoom_archive',
  SYNC_HOUR: 9,
  TIMEZONE: 'America/Chicago',
  DATE_FORMAT: 'yyyy-MM-dd HH:mm:ss',
  ZOOM_LOCATION_PATTERN: 'https?:\\/\\/([\\w.-]+\\.)?zoom\\.us\\/',
  EMAIL_SUBJECT_PREFIX: 'Coaching call recording ',
  EMAIL_SUBJECT_DATE_FORMAT: 'MM/dd/yy',
  EMAIL_BODY_LINE0: 'Hi {firstName},',
  EMAIL_BODY_LINE1: 'We hope you enjoyed your {sessionName} session {meetingDay}!',
  EMAIL_BODY_RECORDING_INTRO: 'The recording of your session can be found here:',
  EMAIL_BODY_RECORDING_LINK_TEXT: 'Session Recording',
  EMAIL_BODY_PARAGRAPH_SUMMARY: "You'll also find the meeting summary attached, which includes key takeaways and a recap of the conversation.",
  EMAIL_BODY_PARAGRAPH_NEXT: "Your next call, We're looking forward to continuing the conversation and supporting your progress.",
  EMAIL_BODY_PARAGRAPH_QUESTIONS: "If you have any questions or would like to dive deeper into anything that was discussed, please don't hesitate to reach out.",
  EMAIL_BODY_SIGNOFF: 'Warm regards,\nKara',
  PRESERVED_COLUMNS: ['email_draft_saved', 'video_url', 'pdf_url', 'audio_url', 'transcript_url', 'chat_url'],
  NON_TRAINING_PRESERVED_COLUMNS: ['video_url', 'pdf_url', 'audio_url', 'transcript_url', 'chat_url'],
  // Event color space: Sage (2), Basil (10)
  COACHING_EVENT_COLOR_IDS: ['2', '10'],
  // Calendar color space: Eucalyptus (7), Basil (8), Pistachio (9), Avocado (10), Sage (13)
  COACHING_CALENDAR_COLOR_IDS: ['7', '8', '9', '10', '13'],
  HEADERS: [
    'event_id',
    'title',
    'program',
    'attendee_first_name',
    'attendee_last_name',
    'location',
    'zoom_meeting_id',
    'start',
    'end',
    'attendee_email',
    'updated',
    'email_draft_saved',
    'video_url',
    'pdf_url',
    'audio_url',
    'transcript_url',
    'chat_url'
  ],
  NON_TRAINING_HEADERS: [
    'event_id',
    'title',
    'program',
    'attendee_first_name',
    'attendee_last_name',
    'location',
    'zoom_meeting_id',
    'start',
    'end',
    'attendee_email',
    'updated',
    'video_url',
    'pdf_url',
    'audio_url',
    'transcript_url',
    'chat_url'
  ]
};

function getConfig_() {
  var props = PropertiesService.getScriptProperties();
  var keys = CONFIG.SCRIPT_PROPERTY_KEYS;
  return {
    eventsSheetName: CONFIG.EVENTS_SHEET_NAME,
    nonTrainingEventsSheetName: CONFIG.NON_TRAINING_EVENTS_SHEET_NAME,
    calendarId: props.getProperty(keys.CALENDAR_ID) || CONFIG.CALENDAR_ID,
    lookbackDays: CONFIG.LOOKBACK_DAYS,
    lookaheadDays: CONFIG.LOOKAHEAD_DAYS,
    archiveAfterDays: CONFIG.ARCHIVE_AFTER_DAYS,
    zoomArchiveSpreadsheetId: props.getProperty(keys.ZOOM_ARCHIVE_SPREADSHEET_ID),
    zoomArchiveSheetName: CONFIG.ZOOM_ARCHIVE_SHEET_NAME,
    syncHour: CONFIG.SYNC_HOUR,
    timezone: CONFIG.TIMEZONE,
    dateFormat: CONFIG.DATE_FORMAT,
    zoomLocationPattern: CONFIG.ZOOM_LOCATION_PATTERN,
    emailSubjectPrefix: CONFIG.EMAIL_SUBJECT_PREFIX,
    emailSubjectDateFormat: CONFIG.EMAIL_SUBJECT_DATE_FORMAT,
    emailBodyLine0: CONFIG.EMAIL_BODY_LINE0,
    emailBodyLine1: CONFIG.EMAIL_BODY_LINE1,
    emailBodyRecordingIntro: CONFIG.EMAIL_BODY_RECORDING_INTRO,
    emailBodyRecordingLinkText: CONFIG.EMAIL_BODY_RECORDING_LINK_TEXT,
    emailBodyParagraphSummary: CONFIG.EMAIL_BODY_PARAGRAPH_SUMMARY,
    emailBodyParagraphNext: CONFIG.EMAIL_BODY_PARAGRAPH_NEXT,
    emailBodyParagraphQuestions: CONFIG.EMAIL_BODY_PARAGRAPH_QUESTIONS,
    emailBodySignoff: CONFIG.EMAIL_BODY_SIGNOFF,
    preservedColumns: CONFIG.PRESERVED_COLUMNS,
    nonTrainingPreservedColumns: CONFIG.NON_TRAINING_PRESERVED_COLUMNS,
    coachingEventColorIds: CONFIG.COACHING_EVENT_COLOR_IDS,
    coachingCalendarColorIds: CONFIG.COACHING_CALENDAR_COLOR_IDS,
    headers: CONFIG.HEADERS,
    nonTrainingHeaders: CONFIG.NON_TRAINING_HEADERS,
    apiKey: props.getProperty(keys.API_KEY),
    driveInboxFolderId: props.getProperty(keys.DRIVE_INBOX_FOLDER_ID),
    clientMeetingsRootFolderId: props.getProperty(keys.CLIENT_MEETINGS_ROOT_FOLDER_ID)
  };
}
