var CONFIG = {
  EVENTS_SHEET_NAME: 'events',
  CALENDAR_ID: 'primary',
  LOOKBACK_DAYS: 7,
  LOOKAHEAD_DAYS: 30,
  ARCHIVE_AFTER_DAYS: 30,
  ZOOM_ARCHIVE_SPREADSHEET_ID: '',
  ZOOM_ARCHIVE_SHEET_NAME: 'zoom_archive',
  SYNC_HOURS: [9, 12, 15, 17],
  TIMEZONE: 'America/Chicago',
  DATE_FORMAT: 'yyyy-MM-dd HH:mm:ss',
  ZOOM_LOCATION_PATTERN: 'https?:\\/\\/([\\w.-]+\\.)?zoom\\.us\\/',
  EMAIL_SUBJECT_PREFIX: 'Coaching call recording ',
  EMAIL_SUBJECT_DATE_FORMAT: 'MM/dd/yy',
  EMAIL_BODY_LINE0: 'Hi {firstName},',
  EMAIL_BODY_LINE1: 'We hope you enjoyed your {sessionName} session {meetingDay}!',
  EMAIL_BODY_RECORDING_INTRO: 'The recording of your session can be found here:',
  EMAIL_BODY_RECORDING_LINK_TEXT: 'Session Recording',
  EMAIL_BODY_PARAGRAPH_SUMMARY: "You'll also find the meeting summary attached, which includes key takeaways and a recap of the conversation.",
  EMAIL_BODY_PARAGRAPH_NEXT: "Your next call, We're looking forward to continuing the conversation and supporting your progress.",
  EMAIL_BODY_PARAGRAPH_QUESTIONS: "If you have any questions or would like to dive deeper into anything that was discussed, please don't hesitate to reach out.",
  EMAIL_BODY_SIGNOFF: 'Warm regards,\nKara',
  PRESERVED_COLUMNS: [
    'email_draft_saved',
    'video_url',
    'pdf_url',
    'audio_url',
    'transcript_url',
    'chat_url',
    'zoom_uuid',
    'video_uuid',
    'pdf_uuid',
    'audio_uuid',
    'transcript_uuid',
    'chat_uuid'
  ],
  RULES_YES_EMAIL: 'yesEmail',
  EMAIL_FLAG_COLUMN: 'email (yes or no)',
  HEADERS: [
    'event_id',
    'title',
    'location',
    'zoom_meeting_id',
    'start',
    'end',
    'attendee_email',
    'updated',
    'email (yes or no)',
    'email_draft_saved',
    'video_url',
    'pdf_url',
    'audio_url',
    'transcript_url',
    'chat_url',
    'zoom_uuid',
    'video_uuid',
    'pdf_uuid',
    'audio_uuid',
    'transcript_uuid',
    'chat_uuid'
  ]
};

function getConfig_() {
  var props = PropertiesService.getScriptProperties();
  return {
    eventsSheetName: CONFIG.EVENTS_SHEET_NAME,
    calendarId: props.getProperty('CALENDAR_ID') || CONFIG.CALENDAR_ID,
    lookbackDays: CONFIG.LOOKBACK_DAYS,
    lookaheadDays: CONFIG.LOOKAHEAD_DAYS,
    archiveAfterDays: CONFIG.ARCHIVE_AFTER_DAYS,
    zoomArchiveSpreadsheetId: props.getProperty('ZOOM_ARCHIVE_SPREADSHEET_ID'),
    zoomArchiveSheetName: CONFIG.ZOOM_ARCHIVE_SHEET_NAME,
    syncHours: CONFIG.SYNC_HOURS.slice(),
    timezone: CONFIG.TIMEZONE,
    dateFormat: CONFIG.DATE_FORMAT,
    zoomLocationPattern: CONFIG.ZOOM_LOCATION_PATTERN,
    emailSubjectPrefix: CONFIG.EMAIL_SUBJECT_PREFIX,
    emailSubjectDateFormat: CONFIG.EMAIL_SUBJECT_DATE_FORMAT,
    emailBodyLine0: CONFIG.EMAIL_BODY_LINE0,
    emailBodyLine1: CONFIG.EMAIL_BODY_LINE1,
    emailBodyRecordingIntro: CONFIG.EMAIL_BODY_RECORDING_INTRO,
    emailBodyRecordingLinkText: CONFIG.EMAIL_BODY_RECORDING_LINK_TEXT,
    emailBodyParagraphSummary: CONFIG.EMAIL_BODY_PARAGRAPH_SUMMARY,
    emailBodyParagraphNext: CONFIG.EMAIL_BODY_PARAGRAPH_NEXT,
    emailBodyParagraphQuestions: CONFIG.EMAIL_BODY_PARAGRAPH_QUESTIONS,
    emailBodySignoff: CONFIG.EMAIL_BODY_SIGNOFF,
    preservedColumns: CONFIG.PRESERVED_COLUMNS,
    rulesYesEmail: CONFIG.RULES_YES_EMAIL,
    emailFlagColumn: CONFIG.EMAIL_FLAG_COLUMN,
    headers: CONFIG.HEADERS,
    apiKey: props.getProperty('API_KEY'),
    driveInboxFolderId: props.getProperty('DRIVE_INBOX_FOLDER_ID'),
    clientMeetingsRootFolderId: props.getProperty('CLIENT_MEETINGS_ROOT_FOLDER_ID')
  };
}
